apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: prometheus-deployment
    env: dev
  name: prometheus
  namespace: prometheus-dev
  # used to attach data
  annotations:
    prometheus.io/scrape: 'true'
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      serviceAccountName: prometheus
      containers:
        - image: prom/prometheus:v1.8.1
          name: prometheus
          # command:
          #   - "bin/prometheus"
          args:
            - "-config.file=/etc/prometheus/prometheus.yml"
            - "-storage.local.path=/prometheus"
            - "-storage.local.retention=24h"
          ports:
            - containerPort: 9090
              protocol: TCP
          volumeMounts:
            - mountPath: "/prometheus"
              name: data
            - mountPath: "/etc/prometheus"
              name: config-volume
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
            limits:
              cpu: 500m
              memory: 2500Mi
      volumes:
        - emptyDir: {}
          name: data
        - configMap:
            name: prometheus.yml
          name: config-volume
